name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Required Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-venv openjdk-17-jdk unzip wget
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Install Android SDK & Build Tools
        run: |
          sudo mkdir -p /opt/android-sdk/cmdline-tools
          cd /opt/android-sdk/cmdline-tools
          
          # Download and install command-line tools
          sudo wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          sudo unzip -q commandlinetools-linux-11076708_latest.zip -d /opt/android-sdk/cmdline-tools
          sudo mv /opt/android-sdk/cmdline-tools/cmdline-tools /opt/android-sdk/cmdline-tools/latest
          sudo rm commandlinetools-linux-11076708_latest.zip

          # Create licenses directory before writing license keys
          sudo mkdir -p /opt/android-sdk/licenses
          
          # Accept licenses
          echo -e "84831b9409646a918e30573bab4c9c91346d8abd\n24333f8a63b6825ea9c5514f83c2829b004d1fee" | sudo tee /opt/android-sdk/licenses/android-sdk-license > /dev/null

      - name: Set Up Android Environment Variables
        run: |
          echo "ANDROID_HOME=/opt/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=/opt/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:/opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/emulator:/opt/android-sdk/build-tools/34.0.0" >> $GITHUB_ENV

      - name: Install Android Platform Tools & AIDL
        run: |
          yes | sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;25.1.8937393"

      - name: Verify AIDL Installation
        run: |
          if [ -f "/opt/android-sdk/build-tools/34.0.0/aidl" ]; then
            echo "AIDL is installed correctly."
          else
            echo "ERROR: AIDL not found!"
            exit 1
          fi

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: built-apk
          path: bin/*.apk
