name: Build APK with Buildozer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk
          pip install --upgrade pip virtualenv
          pip install --user buildozer cython

      - name: Set Environment Variables
        run: |
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Install Android SDK Components  # ✅ Fix for AIDL Not Found
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Verify AIDL Installation
        run: |
          ls $ANDROID_SDK_ROOT/build-tools/34.0.0/
          if [ ! -f "$ANDROID_SDK_ROOT/build-tools/34.0.0/aidl" ]; then echo "❌ AIDL not found!"; exit 1; fi

      - name: Initialize Buildozer (If Needed)
        run: |
          if [ ! -f buildozer.spec ]; then buildozer init; fi

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Built APK
          path: bin/*.apk
