name: Buildozer APK Build

on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk
          pip install --upgrade pip virtualenv
          pip install --user buildozer cython

      - name: Add Buildozer to Path
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Android SDK Build-Tools  # ✅ Fix for AIDL Not Found
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Initialize Buildozer (If Needed)
        run: |
          if [ ! -f buildozer.spec ]; then buildozer init; fi

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Built APK
          path: bin/*.apk
